### ISSUE TITLE
WebAuthenticator not working with Mozilla Firefox

### ISSUE THREAD

**Issue by shv07** [dotMorten/WinUIEx#117]
Hi,

I am using your WebAuthenticator for authenticating a MAUI windows app. The authenticator works correctly with edge and chrome browsers. But when I set Mozilla as default browser, the browser opens, accepts login credentials, brings the app in the foreground but the control is never returned to the MAUI app. 

On Debugging the WebAuthenticator.cs I found this:-
```c#
   // WebAuthenticator.cs
    tasks.Add(taskId, tcs);
    var uri = await tcs.Task.ConfigureAwait(false);
```

Here, the control never returns to the last line after the second last is executed.

Using with Windows 11 and Firefox 111.0.1 (64-bit).

**Comment by dotMorten** [comment]
Thanks that's a good find. However the datastring should already be getting encoded, so I don't really get this. This smells like a firefox bug

**Comment by oliverholliday** [comment]
I'm also getting this in MAUI.

I had to register a key otherwise the state appInstance was always a blank string.

```c#
Microsoft.Windows.AppLifecycle.AppInstance.FindOrRegisterForKey("hello");
```

I think maybe this is a bug? The CheckOAuthRedirectionActivation method has code to set that string, but it returns early if the app activation wasn't by protocol handler.

Even after that, with Firefox as default browser the string is coming back with unquoted strings. Presumably Firefox is stripping them somehow.

```
{appInstanceId:hello,signinId:03a942fd-4e70-4370-8675-881f9b453c41,state:9M3rdrjDoasqASFXF10_Ig}
```

With the following patches applied the authentication completes:

![image](https://github.com/dotMorten/WinUIEx/assets/45265056/6cd17243-abb0-4b3a-ac41-8e545b5f64d6)

**Comment by RobinS-S** [comment]
@dotMorten are you still maintaining this project? This bug is still relevant in the workaround for MAUI's WebAuthenticator in Windows, since the SDK still doesn't handle this properly. If this is fixed, this library can be used as a universal fix for Windows WebAuthenticator.

As far as I can see, the code @shv07 wrote fixes it. However, I would like to suggest another fix: when passing state in the original URL, it does not respect this state and overwrites it. I've changed the code a little bit to restore the original state in the query parameter.

Is his code OK and would you consider merging it? If you do not, I can fork and PR my changes (the same bug fixed and restores original state). What requirements would you have for merging that fix? 
![image](https://github.com/dotMorten/WinUIEx/assets/16294492/41885617-d3a3-4583-9f82-71859dd156ac)

**Comment by dotMorten** [comment]
> are you still maintaining this project?

??? That last release was merely a month ago.
I work in it when I have the time and resources. Installing and working around a bug in Firefox hasn't been a huge priority right now. Considering this is a firefox-specific issue, did anyone open an issue with the Firefox people?

**Comment by RobinS-S** [comment]
> > are you still maintaining this project?
> 
> ??? That last release was merely a month ago. I work in it when I have the time and resources. Installing and working around a bug in Firefox hasn't been a huge priority right now. Considering this is a firefox-specific issue, did anyone open an issue with the Firefox people? I'm quite worried workarounds like this will break other browsers.

I didn't mean to offend you or say you don't spend enough time on it. Sorry if you understood that from it, I only looked at the last commit.

No, I did not open an issue with Firefox, I'm not very familiar with their bug reporting process and don't fully understand the bug. I've tested with Chrome and Edge, my fix doesn't seem to break those browsers, but it does add unnecessary double encoding. I will try to see if I can reproduce the bug and report it at Firefox.

I understand if you don't want to fix this on your side, for now I think it's easier to use a WebView because even when using this package as a workaround, it doesn't work for all browsers.

Thank you for your work on the package regardless!

**Comment by RobinS-S** [comment]
@dotMorten I've tested it out a bit, and found out it is indeed a Firefox problem. Fixing this in your code would be nice to get something working fast, but I agree they should fix it. Reported it at [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1840289).
