### ISSUE TITLE
Add SizeToContent - Proposal

### ISSUE THREAD

**Issue by SkySpiritDev** [dotMorten/WinUIEx#151]
It would be great to have a SizeToContent method on the window so that the window size adjusts to the content.

There is a similar property in WPF.

Thanks.

**Comment by dotMorten** [comment]
Thank you for the suggestion. Unfortunately I don't see a good hook for this at the Window level. You'd need some sort of custom control as the root object that overrides the measure step.
Since I don't see a good obvious solution I can do at the WinUIEx level, I'm closing it here.

I'd suggest logging this feature request in the WinUI repo instead.

**Comment by SkySpiritDev** [comment]
Ok, thanks for feedback.
