### ISSUE TITLE
Latest "Microsoft.Windows.CsWin32" causes compile errors

### ISSUE THREAD

**Issue by HEIC-to-JPEG-Dev** [dotMorten/WinUIEx#8]
Hi, will you be updating this to support the latest release of Microsoft.Windows.CsWin32 as it no longer compiles due to breaking changes in the API (Microsoft.Windows.CsWin32 vs 0.1.506-beta NuGet package causes this).

Also, can you make it available as a NuGet package ?

Thanks

**Comment by dotMorten** [comment]
Is there a reason you need it to be built with the latest CsWin32? Since it's a code generator and doesn't affect other projects referencing this, it shouldn't matter which version I use.
wrt nuget, I'm reluctant as reunion is still work in progress and many of the gaps this project fills are being worked on in WinUI.

**Comment by HEIC-to-JPEG-Dev** [comment]
Thanks for coming back so quickly, much appreciated.

The reason for using the latest is simply because I upgrade all my NuGet packages after a release a new version (with testing); there is an assumption that if a package is updated, there's a reason, and I should probably be using the update.

I understand that as reunion moves forward, features change and become part of the product. Most of the features you offer in this package have been stated as "post 1.0", of course that might change, but Nuget packages are a great way for developers to consume your [great] work and get updates quickly without having to keep checking back to GitHub. 

Don't get me wrong, what I'm saying here is "THANK YOU" as I wouldn't be able to convert HEIC to JPEG to WinUI without your work. I appreciate any work others do, especially for free (I do sponsor other projects I use so I guess that's my contribution).

**Comment by dotMorten** [comment]
I tried the latest CsWin32, and due to [this issue](https://github.com/microsoft/CsWin32/issues/264) it isn't currently possible to use the latest version of it, as we rely on `Shell_NotifyIcon` which seems to be hit by this for some reason. The proposed workaround in that issue adds significant complexity that isn't worth it, and we might just have to roll our own version of `Shell_NotifyIcon` instead.

**Comment by dotMorten** [comment]
Latest is now in use
